In [19]:
import pandas as pd
import hashlib as hl

In [6]:
athlete_regions = pd.read_csv("data/athlete_regions.csv")
athlete_regions.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,_merge
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,China,NaN,both
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,China,NaN,both
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN,Denmark,NaN,both
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Denmark,NaN,both
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,Netherlands,NaN,both

In [16]:
canada = athlete_regions[athlete_regions["region"] == "Canada"]
canada.to_csv("data/canada.csv")
canada.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,_merge
269,140,"William ""Bill"" Abbott Jr.",M,42.0,172.0,80.0,Canada,CAN,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Mixed Three Person Keelboat,NaN,Canada,NaN,both
270,140,"William ""Bill"" Abbott Jr.",M,46.0,172.0,80.0,Canada,CAN,2000 Summer,2000,Summer,Sydney,Sailing,Sailing Mixed Three Person Keelboat,NaN,Canada,NaN,both
279,146,Jeremy Abbott,M,19.0,179.0,71.0,Canada,CAN,1976 Summer,1976,Summer,Montreal,Canoeing,"Canoeing Men's Canadian Doubles, 1,000 metres",NaN,Canada,NaN,both
280,147,Joanne Abbott,F,41.0,160.0,57.0,Canada,CAN,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Mixed Three Person Keelboat,NaN,Canada,NaN,both
281,148,"Kathryn ""Katie"" Abbott",F,21.0,164.0,63.0,Canada,CAN,2008 Summer,2008,Summer,Beijing,Sailing,Sailing Women's Three Person Keelboat,NaN,Canada,NaN,both

In [17]:
canada.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal', 'region', 'notes',
       '_merge'],
      dtype='object')

In [18]:
canada["Name"].head()

269    William "Bill" Abbott Jr.
270    William "Bill" Abbott Jr.
279                Jeremy Abbott
280                Joanne Abbott
281       Kathryn "Katie" Abbott
Name: Name, dtype: object

In [20]:
hashes = canada["Name"].apply(lambda x: hl.sha256(x.encode()).hexdigest())
hashes.head()

269    aba7d8d0992f2b3b6e46b1831df764994ff8ffbf6c898f...
270    aba7d8d0992f2b3b6e46b1831df764994ff8ffbf6c898f...
279    70df8f4a81f7f3a99f3082f342cbc5abe1a94639746d6e...
280    f88877baecbe8c235efe8ad5692bab36d2dc9e36091da0...
281    6dbe76474f9fa17f0569120a314c2fb177ec51f05996eb...
Name: Name, dtype: object

In [21]:
canada.insert(2, "HashName", hashes)
canada.head()

,ID,Name,HashName,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,region,notes,_merge
269,140,"William ""Bill"" Abbott Jr.",aba7d8d0992f2b3b6e46b1831df764994ff8ffbf6c898f...,M,42.0,172.0,80.0,Canada,CAN,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Mixed Three Person Keelboat,NaN,Canada,NaN,both
270,140,"William ""Bill"" Abbott Jr.",aba7d8d0992f2b3b6e46b1831df764994ff8ffbf6c898f...,M,46.0,172.0,80.0,Canada,CAN,2000 Summer,2000,Summer,Sydney,Sailing,Sailing Mixed Three Person Keelboat,NaN,Canada,NaN,both
279,146,Jeremy Abbott,70df8f4a81f7f3a99f3082f342cbc5abe1a94639746d6e...,M,19.0,179.0,71.0,Canada,CAN,1976 Summer,1976,Summer,Montreal,Canoeing,"Canoeing Men's Canadian Doubles, 1,000 metres",NaN,Canada,NaN,both
280,147,Joanne Abbott,f88877baecbe8c235efe8ad5692bab36d2dc9e36091da0...,F,41.0,160.0,57.0,Canada,CAN,1996 Summer,1996,Summer,Atlanta,Sailing,Sailing Mixed Three Person Keelboat,NaN,Canada,NaN,both
281,148,"Kathryn ""Katie"" Abbott",6dbe76474f9fa17f0569120a314c2fb177ec51f05996eb...,F,21.0,164.0,63.0,Canada,CAN,2008 Summer,2008,Summer,Beijing,Sailing,Sailing Women's Three Person Keelboat,NaN,Canada,NaN,both

In [22]:
canada.to_csv("data/canada.csv")